### ISSUE TITLE
Feature Todolist

### ISSUE THREAD

**Issue by aancw** [nsiregar/pegelinux#41]
Please leave on going features or todolist here for easy managing this project and let everyone know which one we will develop.

- [ ] Profile page edit/update 
- [ ] Github Auth
- [ ] Etc

**Comment by nsiregar** [comment]
@aancw kayanya lebih enak satu issue untuk satu fitur, jadi lebih cepet di closenya

**Comment by aancw** [comment]
Gpp, ini cuman rekap aja nantinya. Kayak ngerasa "spam" kalau misal 1-1. Just my 2 cents ya, makanya gue bilang elo aja yang buat issue takutnya beda pandangan.

**Comment by nsiregar** [comment]
kalau dibikin 1-1 nanti bisa kayak pr ini #40 jadi ngerefer ke issue mana yang di-solve-kan. 
untuk buat issue sih ga harus ane, karena fiturkan yang perlu usernya.

**Comment by wildtype** [comment]
Ikut usul deh, buat rekap bikin di wiki aja. Taruh homepage sekalian, jadi sekali liat homepage wiki, langsung ngeh mana yang ongoing, mana yang masih dianggurin, dll. Takutnya kalo di ticket, nanti tenggelam diantara ticket-ticket yang lain.

**Comment by aancw** [comment]
Oke, cuman saran aja awalnya, soalnya kita belum buat todolist untuk ongoing. Gue close ya.
